FROM dsouzd04/himc_rpy2_singlecell:2.0

USER $NB_USER
WORKDIR /home/"${NB_USER}"

RUN \
  python3 -m pip install \
  FlowCal \
  fcswrite \
  pygsheets \
  clustergrammer2 \
  boto3 \
  kneed \
  fcsy[s3]

USER root

RUN \
  jupyter labextension install @jupyter-widgets/jupyterlab-manager

RUN apt-get update && \
  apt-get install -y \
  python3-tk

ENV PATH="${PATH}:/home/jupyteruser/.local/bin"

USER $NB_USER
WORKDIR /home/"${NB_USER}"
